### ISSUE TITLE
Units flagged as deprecated do match "UnitNameRule"

### ISSUE THREAD

**Issue by Ajoschi** [JAM-Software/SonarDelphi#11]
Every Unit flagged as deprecated matches the "UnitNameRule"

Sample:
unit My.Test.Unit deprecated 'Should no longer be used!';
...
-> UnitNameRule matches, which is not reasonable in my opinion (False positive)

**Comment by joachimmarder** [comment]
@Ajoschi: I just recognized that newer versions of the compiler accept the string after deprecated, but in opposite to other deprecated flags the compiler does not add the string to the warnings. So there is currently no benefit in having this string, compare to a comment.

**Comment by joachimmarder** [comment]
Unit for testing:
[Unit2.zip](https://github.com/JAM-Software/SonarDelphi/files/8991831/Unit2.zip)
