### ISSUE TITLE
Move this project to a dedicated organization to combine efforts

### ISSUE THREAD

**Issue by Laurensvanrun** [JAM-Software/SonarDelphi#18]
Hi,

More than a year ago I revitalized the `SonarDelphi` project that had been inactive for too long and was not compatible anymore with the newest SonarQube. Now I see that you (JAM-Software / @joachimmarder) do a lot of development and that is really great to see!

I would like to invite you to combine efforts and move this project to a dedicated 'Organization' (eg. `SonarDelphi`) so that we can centralize all effort. What do you think of this idea?

Best regards, Laurens

**Comment by Laurensvanrun** [comment]
Hi @joachimmarder , if the Virtual TreeView gets a lot of attention it would be worth to keep it up-to-date in your repository. If you want to give me read access, I'm happy for now. I also connected you on LinkedIn.

**Comment by joachimmarder** [comment]
@Laurensvanrun: I sent you an invitation.
