### ISSUE TITLE
ConstructorWithoutInheritedStatementRule should not match for class constructors

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/SonarDelphi#2]
inherited class constructors are called anyway as part of the initialization section of their unit.

**Comment by joachimmarder** [comment]
First add a test case to `src\test\java\org\sonar\plugins\delphi\pmd\ConstructorWithoutInheritedStatementRuleTest.java` and make sure it fails.

**Comment by joachimmarder** [comment]
Unit for testing:
[Unit2.zip](https://github.com/JAM-Software/SonarDelphi/files/8991848/Unit2.zip)

**Comment by x3ntrix** [comment]
@joachimmarder: The provided example it for issue #11, and not this one.

**Comment by joachimmarder** [comment]
Sorry @x3ntrix, I picked the wrong file. I have now updated my comment.
