### ISSUE TITLE
Downloading the plugin in the .jar file

### ISSUE THREAD

**Issue by Malgosiatobiasz1** [JAM-Software/SonarDelphi#30]
Can you please upload the plugin in .jar format for download? I need to install it in Sonarqube helm chart which supports plugins in .jar format. Thanks in advance.

**Comment by joachimmarder** [comment]
This project was forked by Embarcadero which is now the new official home of SonarDelphi: https://github.com/Embarcadero/SonarDelphi

The jar file is available, it is just zipped.

**Comment by Malgosiatobiasz1** [comment]
I would like to ask if the SonarDelphi plugin is compatible with sonarqube-dce-6.0.0 helm chart.

**Comment by x3ntrix** [comment]
> I would like to ask if the SonarDelphi plugin is compatible with sonarqube-dce-6.0.0 helm chart
https://github.com/SonarSource/helm-chart-sonarqube/tree/sonarqube-6.0.1-sonarqube-dce-5.0.1/charts/sonarqube-dce . 
Not sure. You will have to try it out.
> Would it be a big problem to make a plugin available for download in .jar format, not zipped, due to the fact that plugins are installed via helm chart in .jar format?
I added the jar file for the latest release to the release section. But as already said, Embarcadero created a fork which is the new official home. We are not planing on making any new releases in this repository.

**Comment by Malgosiatobiasz1** [comment]
Thank you very much for adding possibility to download .jar file.
